### ISSUE TITLE
Issue when using async actions.

### ISSUE THREAD

**Issue by payman81** [justeat/JE.TurningPages#1]
When I add the following handler 
`config.MessageHandlers.Add(new PaginationLinkHeaderEnrichment());`

I get a deadlock for async actions

Here is the action: 

```
public async Task<IHttpActionResult> Search()
{
   var result = await Task.Factory.StartNew(() => Task.Delay(1000));
   return Ok();
}
```

**Comment by petemounce** [comment]
@payman81 The tests are green; if this is representative of the break for you, please merge & release next version? Apologies; async newbie.

**Comment by payman81** [comment]
@petemounce All is working for me.
